Support DruidSQL multi-value string functions
implydata/plywood pull request #244
Opened 2022-07-07 17:16 UTC by QSSS

### Summary

This PR introduces two Plywood expressions that are associated to the following two DruidSQL multi-value string functions: 
1. MV_CONTAINS
2. MV_OVERLAP
3. MV_FILTER_ONLY

based on https://druid.apache.org/docs/0.23.0/querying/sql-multivalue-string-functions.html.

Key code changes
1. Added mvContainsExpression, mvOverlapExpression, and mvFilterOnlyExpression.
2. Added a helper function `stringArrayToSQL` to handle parsing the multi-value string to SQL string.
4. Added tests in `expression.mocha` ,`simulateDruidSql.mocha`, `simulatedDruid.mocha`

2022-07-07 18:03 UTC, tylerreece22 requested changes

2022-07-07 19:52 UTC, jgoz commented on src/dialect/mySqlDialect.ts
> +  public mvContainsExpression(_a: string, _b: string): string {
Yeah, this can be removed

2022-07-07 19:52 UTC, jgoz commented on src/dialect/postgresDialect.ts
> +  public mvContainsExpression(_a: string, _b: string): string {
Can also be removed

2022-07-07 19:59 UTC, jgoz commented on src/expressions/mvContainsExpression.ts
> +    this._checkExpressionTypes('STRING');
```suggestion
    this._checkExpressionTypes('STRING', 'SET/STRING');
```

Per the docs:
> Returns 1 if the array contains the element specified by expr, or contains all elements specified by expr if expr is an array, else 0.

Which I think means that the expression could be an array of items.

2022-07-07 19:59 UTC, jgoz commented on src/expressions/mvContainsExpression.ts
> +  }
Is this helper actually necessary? And if it is, should it be `operandValue.mvContains(expressionValue)`?

2022-07-07 19:59 UTC, jgoz commented on src/expressions/mvOverlapExpression.ts
> +    this._checkExpressionTypes('STRING');
```suggestion
    this._checkOperandTypes('SET/STRING');
    this._checkExpressionTypes('SET/STRING');
```

Per the docs, I think both of these are supposed to be arrays?

> Returns 1 if arr1 and arr2 have any elements in common, else 0.

2022-07-07 19:59 UTC, jgoz commented on src/expressions/mvOverlapExpression.ts
> +    return operandValue.overlap(expressionValue);
Same here - is this necessary and if so, should it be `mvOverlap`?

2022-07-08 15:56 UTC, jgoz approved these changes
🍣

2022-07-08 16:52 UTC, tylerreece22 approved these changes
🧠

2022-07-11 14:37 UTC, merged